___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [162]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [163]:
my_list = [5, 10, 15, 20, 25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [164]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [165]:
arr = np.ones((4,4), dtype = int)

#### 5. Make all the values of the array above 7

In [166]:
arr[:,:]=7
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [167]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [168]:
np.arange(2,16,2)

array([ 2,  4,  6,  8, 10, 12, 14])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [169]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [170]:
np.linspace(0,24,25, dtype= int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [171]:
np.random.randint(1000,size=5)

array([741, 926, 467, 208, 176])

#### 11. Create random normal distributed 5x5 array

In [172]:
np.random.randn(5,5)

array([[-0.64377925, -0.98843222,  1.00088765, -0.72014542, -0.60871512],
       [-0.96303289, -0.69622979,  0.09004085,  0.51177804,  0.48946583],
       [ 0.62714939, -0.4642252 , -0.75696662, -0.32729221, -0.15425563],
       [-0.32395303, -0.6981608 ,  0.45677208,  0.27748263, -1.77695582],
       [ 0.060596  , -2.01087166,  0.03876689, -0.71785005,  1.9583122 ]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [173]:
np.random.randint(20,50, size = (3,4))

array([[22, 40, 48, 44],
       [41, 30, 44, 39],
       [44, 25, 40, 49]])

#### 13. Reshape the array below with shape 6x8

In [174]:
ranarr = np.random.randint(2,52, size = (6,8))
ranarr

array([[36, 16, 12, 24, 23, 27, 27,  8],
       [12, 23, 30, 41, 32, 14, 50, 30],
       [11, 47, 37, 17, 25,  9,  5, 26],
       [17, 48, 37, 38, 29, 51, 42, 34],
       [23, 27, 43, 11, 26, 12, 25, 44],
       [22, 24, 35, 10, 22,  3, 14, 11]])

In [175]:
#reshape with -1
ranarr.reshape(4,12)

array([[36, 16, 12, 24, 23, 27, 27,  8, 12, 23, 30, 41],
       [32, 14, 50, 30, 11, 47, 37, 17, 25,  9,  5, 26],
       [17, 48, 37, 38, 29, 51, 42, 34, 23, 27, 43, 11],
       [26, 12, 25, 44, 22, 24, 35, 10, 22,  3, 14, 11]])

## Numpy Indexing and Selection


In [176]:
#Create array below
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [177]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [178]:
mat[0:,0:1]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

#### 16. Get the values in 2nd row for every 2 step.

In [179]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [180]:
mat[1][[0,2]]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [181]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [182]:
mat[:,2] = [77, 77, 77, 77]
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [183]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [193]:
mat[1:4:2,0:3:2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [ ]:
mat[:,2] = [77, 77, 77, 77]
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
a1 = mat[mat<10]
a1

array([1, 2, 4, 5, 6, 8, 9])

In [187]:
a2 = mat[mat>12]
a2

array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
a3 = np.add(a1,a2)
a3

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [ ]:
np.std(a3)

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
sum(mat[:,1])

32

#### 23. Get the median,mean and std of 3rd row from array above

In [ ]:
mat[:,2] = [3,7,11,15]

In [ ]:
a4 = mat[2]
a4

array([ 9, 10, 11, 12])

In [ ]:
#median
np.median(a4)

10.5

In [ ]:
#mean
np.mean(a4)

10.5

In [ ]:
#std
np.std(a4)

1.118033988749895

# Pandas Section

In [99]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [124]:
sal=pd.read_csv('SalariesV.csv')

C:\Users\sumey\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (3,4,5,6,12) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [125]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

In [126]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148049 non-null  object 
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB


In [128]:
sal.describe()

Id       TotalPay  TotalPayBenefits           Year  Notes
count  148654.000000  148654.000000     148654.000000  148654.000000    0.0
mean    74327.500000   74768.321972      93692.554811    2012.522643    NaN
std     42912.857795   50517.005274      62793.533483       1.117538    NaN
min         1.000000    -618.130000       -618.130000    2011.000000    NaN
25%     37164.250000   36168.995000      44065.650000    2012.000000    NaN
50%     74327.500000   71426.610000      92404.090000    2013.000000    NaN
75%    111490.750000  105839.135000     132876.450000    2014.000000    NaN
max    148654.000000  567595.430000     567595.430000    2014.000000    NaN

**How many different year value are there**

In [129]:
sal['Year'].value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [130]:
#max
sal['TotalPay'].max()

567595.43

In [131]:
#avg
sal['TotalPay'].mean()

74768.32197169267

**How many records are there which have TotalPay bigger than avg TotalPay**

In [132]:
len(sal[sal['TotalPay'] > (sal['TotalPay'].mean())][['TotalPay']])

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [133]:
sal.iloc[2][['TotalPayBenefits']]

TotalPayBenefits    335279.91
Name: 2, dtype: object

**Who is lowest paid person**

In [144]:
sal[sal['TotalPay'] == (sal['TotalPay'].min())]['EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [145]:
sal['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

In [146]:
sal['JobTitle'].nunique()

2159

**List 3 least common Jobs**

In [137]:
sal.groupby('JobTitle')['JobTitle'].count().min()

1

In [148]:
sal['JobTitle'].value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [149]:
sal[(sal['TotalPayBenefits'] > (sal['TotalPayBenefits'].mean()))&(sal['Year'] == 2012)]['TotalPayBenefits'].count()

20366

**How many people have the word Manager in their job title?**

In [151]:
sal['EmployeeName'][sal['JobTitle'].apply(lambda x :  'Manager' in x or 'MANAGER'  in x)].count()

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [156]:
sal_new = sal.iloc[:,[0,1,2,7,8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [158]:
sal_new = sal.loc[:,['EmployeeName','JobTitle','TotalPay','TotalPayBenefits']]
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [161]:
sal['EmployeeName'][sal['TotalPayBenefits'].apply(lambda x : (sal['TotalPayBenefits'].min()) < x < (sal['TotalPayBenefits'].mean()))]

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object